# Open-ended answer pools per latent segment. Slots: {course}, {n}, {topic}
COURSES = ["Statistics 2", "Programming 1", "Research Methods", "Cognitive Science", "Data Mining",
           "Machine Learning", "Marketing Analytics", "Corporate Finance", "Constitutional Law",
           "Developmental Psychology", "Philosophy of Mind", "Text Mining", "Linear Algebra",
           "Consumer Behaviour", "Ethics of AI", "the thesis circle", "Intro to Economics",
           "Human-Computer Interaction", "Deep Learning", "Qualitative Methods"]
TOPICS = ["gradient descent", "the ANOVA assumptions", "recursion", "the case law on privacy",
          "attention mechanisms", "the discounting formula", "coding the interviews", "the CLT"]

FRUSTRATE = {
 "sprinter": [
  "Wanted to check if my {course} grade was in during the break. The app showed the assignment as 'graded' but the number only appeared after I logged in on my laptop that evening.",
  "Got a push notification at 23:40 about a new announcement, opened it and it was a reminder that the lecture room changed... for a lecture that was already over.",
  "Tried to submit the {course} assignment from my phone 10 minutes before the deadline. The file picker didn't let me pick the PDF from my drive and I had to run to the library.",
  "The To-do list showed 3 items due but two of them were undated things from a course that finished last block. I almost missed the one that mattered.",
  "I get like {n} emails a day from Canvas. I stopped reading them, and then I missed a change in the deadline for {course}.",
  "Looking for the room number for the {course} exam. It was in an announcement from 3 weeks ago and the app search didn't find it. A friend sent a screenshot on WhatsApp.",
  "Wanted to see what is due this week across all my courses. The dashboard cards each show something different and the calendar only shows things the teacher put a date on.",
  "The app logged me out again and the 2FA code took forever. By the time I was in I forgot what I wanted to check.",
  "Grades for {course} came in for everyone else but mine said 'submitted' for two days. Turned out I had uploaded the wrong file and nobody told me.",
  "Tried to find the slides for last week on my phone. Modules is a giant list, you scroll for ages, and half the folders are named 'Week X' and half 'Lecture X'.",
  "Deadline was at 23:59 but the app showed a different time after I came back from holiday. I panicked and submitted at 22:00 just to be safe.",
  "Notification said 'new comment on your submission'. I opened it, no comment visible. Had to open it on a laptop to see the feedback.",
  "I wanted to quickly check if the lecture was cancelled. Had to go dashboard > course > announcements > scroll. Three taps too many when you are on the bus.",
  "Discussion post for {course} counted as an assignment, so it showed up in my grades as 0 for a week and freaked me out.",
  "Every course puts the deadlines in a different place. One uses Assignments, one uses a PDF planning, one only mentions it in the lecture.",
  "Checking my grade for the {course} midterm: the number was there but the class average was hidden, so I couldn't tell if a 6.1 was good or bad.",
  "The app shows the To-do list but tapping an item opens a web view where I have to log in again.",
  "Wanted to see if the {course} quiz was still open. Had to open the course, then Quizzes, then scroll. On the phone it kept reloading.",
 ],
 "scholar": [
  "I was looking for the reading list for week 4 of {course}. One lecturer puts readings in Modules, another in Files, another in a PDF under Syllabus. I spent 15 minutes clicking around.",
  "Downloaded all the slides for {course} to make notes; every file had a different naming scheme, so sorting them in my notes app was manual work.",
  "The recordings for {course} are in a separate tool that opens in a new tab, and the link is buried in a module item with no thumbnail. I bookmark it because I can never find it twice.",
  "Search in Canvas only searches the current course, and only some things. I wanted a formula from a slide two weeks ago and ended up opening every PDF.",
  "Trying to see the deadlines of all courses in one view. Exported the calendar feed to Google Calendar, but half the assignments had no dates so they never appeared.",
  "A file was replaced by the lecturer, but the old version was still cached in the app. I studied the wrong version for a day.",
  "Discussions are a mess for seminar prep: threads collapse, and there's no way to see what changed since I last visited.",
  "Modules is one long scroll. There is no overview of the course structure, no 'you are here' and no way to collapse everything with one click.",
  "I wanted to re-watch the part of the {course} lecture about {topic}. No chapters, no transcript search, so I scrubbed through 90 minutes.",
  "The syllabus page was empty in 3 of my 4 courses. The actual course guide was a PDF somewhere in Files.",
  "Annotating a PDF in the built-in viewer is impossible, and downloading each one separately to Zotero takes forever.",
  "Notifications for every reply in a discussion I posted in once. Had to dig into settings to find out how to mute one course.",
  "Wanted to compare my rubric score with the criteria. They open in a side panel that cuts off the text, and the comments were in yet another tab.",
  "Group project files were spread across Canvas groups, Google Drive and WhatsApp. Canvas Collaborations didn't work with our university accounts.",
  "For {course} the lecturer uploaded v1, v2 and v2_final of the slides in the same folder. No way to tell which one is current without opening all three.",
  "I keep a Notion page per course because the Canvas page for {course} has no structure I can rely on.",
 ],
 "juggler": [
  "Between work shifts I checked my email and saw a Canvas mail from Monday saying the {course} deadline was moved earlier. I had already planned my weekend around the old date.",
  "I can only study on Sunday. I opened Canvas and had {n} unread announcements from 4 courses. No way to see which ones actually require me to do something.",
  "Missed a group meeting because the invite was only posted in the Canvas group discussion, and I don't get emails for those.",
  "Wanted to watch the recording of a lecture I missed because of work. It was uploaded four days later, with no notification.",
  "I submitted the {course} assignment from my phone during my lunch break and got no confirmation email. Spent the whole shift wondering if it went through.",
  "Deadlines at 23:59 on weekdays are hard when you work evenings. I found out about the {course} quiz window on the day it closed.",
  "Every course sends the same info in a different way. I have a paper list of what to check where, and it still fails.",
  "Emails from Canvas all look the same, 'New announcement in course X'. The important one about exam registration got lost between reminders.",
  "Tried to catch up on {course} after two weeks with my kid sick. There's no 'what did I miss' view, so I opened every module item one by one.",
  "Can't find where the lecturer said what is graded and what is optional. It was mentioned in the lecture I missed.",
  "The Canvas app doesn't show announcement attachments properly, and I'm mostly on my phone during the week.",
  "I wanted to see my total workload for the block. Nothing in Canvas shows that; I ended up building a spreadsheet.",
  "Came back after a week of night shifts and the {course} module for that week had 14 items. Which of these do I actually need before the tutorial?",
  "Notification emails arrive during my working hours and are gone from my head by the evening. I have missed two small deadlines that way.",
 ],
 "power": [
  "Setting up the {course} course for the new year: copying the course from last year carried over old due dates that I had to fix one by one, 22 assignments.",
  "Grading 180 submissions in SpeedGrader: the page reloads for every student and the rubric panel collapses each time. Two clicks that cost me hours.",
  "Students emailed me at 23:50 because the upload failed. I could not see any error on my side, the submission just wasn't there.",
  "Wanted to send a message to only the students who hadn't submitted yet. The option exists but it is hidden three menus deep.",
  "Making groups for the project: the random assignment didn't respect the tutorial sections, so I did it in Excel and re-entered it.",
  "Peer review assignment: I could not see who was assigned to whom without opening every submission.",
  "Uploading lecture recordings means going to another platform, then linking back. Half the students never find the link.",
  "I get an email for every single submission. I turned notifications off, and then missed a student's question in the Inbox for a week.",
  "The gradebook export used commas as decimal separators in some columns and dots in others, and the import back rejected half of them.",
  "Quiz question banks: I edited a question and it silently didn't update in the quiz that already used it.",
  "Wanted to see which students had not opened the course in two weeks. The analytics page is slow and doesn't let me filter by tutorial group.",
  "An announcement I scheduled for Monday 08:00 went out Sunday evening because the time zone reverted. Students thought there was a change of plan.",
  "Re-using a rubric across two courses: you can, but the rubric gets duplicated and any fix must be repeated.",
  "Students in {course} kept asking where the slides were. They were in Modules, published, but the course navigation still showed Files first.",
  "Extending a deadline for three students with an arrangement means editing the assignment, adding a section override, and hoping the dates don't shift for everyone else.",
 ],
 "reluctant": [
  "I wanted to upload the slides after the lecture. It asked whether to put them in Files or Modules or Pages. I still don't know the difference; the TA fixed it later.",
  "Tried to publish the course before the block started. Everything looked fine to me but students said it was invisible. There was a small 'unpublished' icon I did not see.",
  "Sending an announcement: I wrote it, clicked something and it disappeared. The second time I wrote it in Word first.",
  "I wanted to enter grades. The gradebook has dozens of columns and I entered them in the wrong assignment column. The education office had to help.",
  "Every year the interface has changed a little and the button I remember is somewhere else.",
  "A student asked me a question through the Canvas Inbox. I only saw it three weeks later because I read my normal email, not that one.",
  "I do not use the calendar; my secretary keeps my agenda. But students expect the deadlines to be in Canvas, so there is always a mismatch.",
  "I tried to see who was in my tutorial group. The People page listed 300 students from all sections and I could not filter them.",
  "Uploading a 200 MB recording failed twice without any message.",
  "The system asked me to set up two-factor authentication on a new phone in the middle of a lecture.",
  "Honestly I avoid it. I email the students the PDFs and ask the TA to put them in Canvas.",
  "I wanted to reply to a student's comment on a submission and could not find where to type. Ended up emailing them.",
 ],
 "access": [
  "The Modules page reads like a list of 200 links to my screen reader; the headings are not marked as headings so I cannot jump between weeks.",
  "Lecture recordings for {course} have auto-captions that turn 'Bayesian' into 'basin'. I stopped watching them and asked for the slides instead.",
  "Scanned PDFs uploaded as images: my screen reader reads nothing, and the text-to-speech I use for dyslexia can't read them either.",
  "The grey-on-white text in the To-do list and the tiny date labels are unreadable for me without zooming, and then the layout breaks.",
  "A timed quiz did not give me my extra time even though it was arranged; the setting is per quiz and the lecturer forgot.",
  "Drag and drop to reorder my dashboard cards is the only way, and I can't drag precisely.",
  "The rich content editor moves focus when I type in a discussion post; with the screen reader I lose my place every few words.",
  "Videos with no transcript and no captions in {course}; the lecture was the only place where the exam format was explained.",
  "Long announcements are one wall of text with no headings, hard for me to parse. I copy them into a reader app first.",
  "The colour-only 'submitted / late / missing' labels in Grades. I cannot tell the states apart quickly.",
  "Keyboard navigation in the calendar traps you in the month grid; I couldn't get to the assignment link.",
  "Trying to enlarge the text on my phone: the app ignores the system font size setting.",
 ],
 "staff": [
  "Students come to the desk asking where a grade is and I can't see what they see, so I ask them to turn their laptop around.",
  "Enrolments sync overnight. A student who registered in the morning cannot see the course until the next day and comes to us, upset.",
  "In week 1 we answer 'where are the slides' about fifty times because every course puts them somewhere else.",
  "A lecturer asked us to fix due dates in 30 assignments after a course copy. There is no bulk edit that works reliably.",
  "We maintain a course template, but lecturers can delete the structure with one click and then the support questions start.",
  "Checking whether a student really submitted before the deadline: the submission log is hard to read and the time zone is ambiguous.",
 ],
 "generic": [
  "It logged me out and I lost the text of a long post.",
  "Could not find the exam location; it was in an announcement, not in the calendar.",
  "The dashboard shows courses from last year first.",
  "Slow to load on the campus wifi, especially the Files page.",
 ],
}

HELPED = {
 "sprinter": [
  "The push notification that my {course} grade was published, right when I was on the train.",
  "The To-do list saved me once: I had forgotten about a quiz and it was there.",
  "Submitting a photo of my handwritten answers from the app worked surprisingly smoothly.",
  "Seeing the exact time left before a deadline on the assignment page.",
  "The announcement about the room change came right before the lecture; I would have gone to the wrong building.",
  "When the teacher replied to my comment on my submission I saw it immediately in the app.",
  "Checking a grade in 5 seconds while waiting for coffee.",
 ],
 "scholar": [
  "The Modules page for {course} was set up week by week with readings, slides and the recording in one place. That is how every course should look.",
  "The calendar feed into Google Calendar, once the lecturer actually dated everything.",
  "Downloading all files of a module in one zip.",
  "A rubric with comments per criterion made the feedback actually useful.",
  "Recordings with the slide timeline let me jump to the part I needed.",
  "A discussion where the lecturer pinned the answers to common questions before the exam.",
  "Having every submission I ever made in one place when I wrote my thesis.",
 ],
 "juggler": [
  "Recordings. Without them I could not follow the course while working.",
  "The e-mail digest once a day instead of every announcement, once I found the setting.",
  "Being able to submit from my phone during a break.",
  "The lecturer of {course} posted a weekly 'what to do this week' announcement. In that course I never fell behind.",
  "An extension request through the assignment page; the teacher approved it within an hour.",
  "Seeing on Sunday evening exactly what is due in the coming week, at least for the courses that date their assignments.",
 ],
 "power": [
  "SpeedGrader with a rubric: grading 60 essays in an afternoon, with reusable comments.",
  "Scheduling all announcements for the block in one go.",
  "Quiz auto-grading for the weekly checks saves me hours per week.",
  "Copying a course from last year, even with the date problem, beats starting from scratch.",
  "Seeing at a glance who has not submitted and messaging them in one go.",
  "The analytics showed me that half the class had not opened the reader before the seminar, so I changed the plan.",
  "Students see their grades and feedback at the same moment, no more 200 emails.",
 ],
 "reluctant": [
  "The TA set everything up and I only had to click publish.",
  "Students could see the slides right after the lecture without me emailing them.",
  "Announcements reach everybody at once, unlike my email list which is always outdated.",
  "Nothing comes to mind, honestly.",
  "Grades were visible to students without me having to send them individually.",
 ],
 "access": [
  "One lecturer added proper headings and alt text in {course}; I could navigate the whole course by headings for the first time.",
  "Transcripts of the {course} recordings were edited by the TA, so I could actually search them.",
  "The extra time setting worked for the exam quiz once the lecturer set it.",
  "The immersive reader in my browser works fine on Canvas pages when they are real text.",
  "Being able to download the PDF and open it in my own reader instead of the built-in viewer.",
 ],
 "staff": [
  "The course template we push to all courses in our school makes the support questions drop noticeably.",
  "Being able to look up a student's course list when they are at the desk.",
  "Masquerading as a student to see exactly what they see, when we are allowed to.",
 ],
 "generic": [
  "Not much, it does the job.",
  "Reminders for deadlines.",
  "Nothing specific.",
  "",
  "",
 ],
}

MORE = {
 "sprinter": ["Just make everything work on the phone.", "One overview of all deadlines for all courses please.",
              "Fewer emails, more useful pushes.", "Let me see the class average next to my grade.", "Dark mode.",
              "I basically live in WhatsApp groups for each course; that's where the real info is.", "", "", "", ""],
 "scholar": ["Consistency between courses would fix most of my problems.", "Let me search across all courses and inside PDFs.",
             "I use Notion for everything and Canvas is just the place where files live.", "Please make lecturers date their assignments.",
             "A proper reading list with status (read / to read) would be great.", "", "", "", ""],
 "juggler": ["A weekly digest of what changed and what is due.", "Recordings uploaded the same day.",
             "I work 24 hours a week; my study time is Sunday and Wednesday evening. Anything that makes catching up faster helps.",
             "Deadlines on Friday 17:00 instead of Sunday 23:59 would help students with jobs.",
             "I have two kids. I need to know in one minute whether anything changed.", "", "", "", ""],
 "power": ["Bulk actions everywhere: due dates, messages, rubrics.", "Better analytics per tutorial group.",
           "Groups that respect sections.", "Notification settings per course and per type.",
           "I spend more time on course admin than on teaching content.", "", "", ""],
 "reluctant": ["A simple mode with only the five things I actually do.", "Training once a year is not enough; I need help at the moment I am doing it.",
               "I rely on my TA for everything in Canvas.", "Let students see my office hours easily.", "", "", "", ""],
 "access": ["Accessibility depends entirely on the lecturer. The system should enforce headings, alt text and captions.",
            "Let me set my own font size and contrast once, for all courses.",
            "Ask disabled students before you design; we are not an edge case.", "", ""],
 "staff": ["Support staff need a view of what the student sees.", "Fewer places to put the same information.", "", ""],
 "generic": ["", "", "", "No.", "Good luck with the project!"],
}
